### ISSUE TITLE
validate-all.sh: a fresh crash on 000069

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-datasets#30]
I have made a run of it on drogon (under dandi account in a screen) and it all went fine until
```
Processing dandisets/000069/sub-anm106211/sub-anm106211_behavior+icephys.nwb
pynwb validation errors for /mnt/backup/dandi/dandisets/000069/.git/annex/objects/ZQ/XQ/SHA256E-s297607244--fe7ac132d5bcbb98ec351d057e261b84c1f44dd8212c87fe5a2d2a7118e79ed1.nwb/SHA256E-s297607244--fe7ac132d5bcbb98ec351d057e261b84c1f44dd8212c87fe5a2d2a7118e79ed1.nwb: []
VALIDATION ERROR: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 122, in <module>
    main()
  File "tools/populate_dandiset_asset_yamls.py", line 80, in main
    with validation_errs.open("a") as fp:
  File "/home/dandi/miniconda3/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/dandi/miniconda3/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '000069/VALIDATION.errors'
```

**Comment by bendichter** [comment]
Let me know if this is due to a problem with the dataset or pynwb

**Comment by yarikoptic** [comment]
Thank you @bendichter but I think it is on dandi side.
